#!/vendor/bin/sh
#
# Copyright (C) 2021-2026 12X
#

BASEDIR="$(dirname $(readlink -f "$0"))"
. $BASEDIR/pathinfo.sh
. $BASEDIR/libcommon.sh
. $BASEDIR/libuperf.sh

is_writable_knob() {
    local f="$1"
    [ -f "$f" ] || return 1
    local cur
    cur="$(cat "$f" 2>/dev/null)" || return 1
    echo "$cur" >"$f" 2>/dev/null || return 1
    return 0
}

find_gpu_devfreq_pair() {
    local base
    for base in \
        /sys/class/kgsl/kgsl-3d0/devfreq \
        /sys/class/devfreq/*kgsl* \
        /sys/class/devfreq/*adreno* \
        /sys/class/devfreq/*gpu*; do
        [ -f "$base/min_freq" ] || continue
        [ -f "$base/max_freq" ] || continue
        if is_writable_knob "$base/min_freq" && is_writable_knob "$base/max_freq"; then
            GPU_MIN_NODE="$base/min_freq"
            GPU_MAX_NODE="$base/max_freq"
            return 0
        fi
    done
    return 1
}

patch_gpu_knob_path() {
    local cfg="$USER_PATH/uperf.json"
    [ -f "$cfg" ] || return 0

    local min_node
    local max_node
    if find_gpu_devfreq_pair; then
        min_node="$GPU_MIN_NODE"
        max_node="$GPU_MAX_NODE"
        echo "GPU knob detected: $min_node / $max_node"
    else
        min_node="/dev/null"
        max_node="/dev/null"
        echo "No writable GPU devfreq node found, disable GPU freq writes."
    fi

    sed -i "s|\"gpuMinFreq\": \"[^\"]*\"|\"gpuMinFreq\": \"$min_node\"|g" "$cfg"
    sed -i "s|\"gpuMaxFreq\": \"[^\"]*\"|\"gpuMaxFreq\": \"$max_node\"|g" "$cfg"
}

mode_for_pkg() {
    case "$1" in
    tv.danmaku.bili | \
    com.google.android.youtube | \
    com.google.android.apps.youtube.music | \
    com.qiyi.video | \
    com.qiyi.video.pad | \
    com.tencent.qqlive | \
    com.youku.phone | \
    com.cmcc.cmvideo | \
    com.netflix.mediaclient | \
    com.amazon.avod.thirdpartyclient | \
    com.disney.disneyplus | \
    com.hulu.plus | \
    com.mxtech.videoplayer.ad | \
    com.mxtech.videoplayer.pro | \
    com.ss.android.article.video | \
    com.ss.android.ugc.aweme | \
    com.ss.android.ugc.aweme.lite | \
    com.smile.gifmaker | \
    com.kuaishou.nebula)
        echo "powersave"
        ;;
    *)
        echo "balance"
        ;;
    esac
}

list_installed_packages() {
    if command -v cmd >/dev/null 2>&1; then
        local out
        out="$(cmd package list packages 2>/dev/null | sed -n 's/^package://p')"
        if [ -n "$out" ]; then
            echo "$out"
            return 0
        fi
    fi
    pm list packages 2>/dev/null | sed -n 's/^package://p'
}

regen_complete_perapp_rules() {
    local outfile="$USER_PATH/perapp_powermode.txt"
    local tmpfile="$outfile.tmp"
    local pkgs
    pkgs="$(list_installed_packages | tr -d '\r' | sed '/^$/d' | sort -u)"
    [ -n "$pkgs" ] || {
        echo "Package list unavailable, keep existing per-app rules."
        return 0
    }

    echo "# Auto generated by Uperf-12X." >"$tmpfile"
    echo "# Generated at: $(date '+%Y-%m-%d %H:%M:%S %z')" >>"$tmpfile"
    echo "# Every installed package is explicitly assigned to avoid missed intervention." >>"$tmpfile"
    echo "# This file is regenerated on each boot." >>"$tmpfile"
    echo "" >>"$tmpfile"

    local pkg
    local mode
    local pkg_cnt=0
    for pkg in $pkgs; do
        mode="$(mode_for_pkg "$pkg")"
        echo "$pkg $mode" >>"$tmpfile"
        pkg_cnt=$((pkg_cnt + 1))
    done

    echo "" >>"$tmpfile"
    echo "- powersave" >>"$tmpfile"
    echo "* balance" >>"$tmpfile"
    mv -f "$tmpfile" "$outfile"
    chmod 0644 "$outfile"
    echo "Generated complete per-app rules: $pkg_cnt packages."
}

$BIN_PATH/busybox/busybox --install -s $BIN_PATH/busybox

cp -af $SCRIPT_PATH/vtools_powercfg.sh /data/powercfg.sh
cp -af $SCRIPT_PATH/vtools_powercfg.sh /data/powercfg-base.sh
cp -af $SCRIPT_PATH/powercfg.json /data/powercfg.json
chmod 755 /data/powercfg.sh
chmod 755 /data/powercfg-base.sh
echo "sh $SCRIPT_PATH/powercfg_main.sh \"\$1\"" >>/data/powercfg.sh

wait_until_login

sh $SCRIPT_PATH/powercfg_once.sh
regen_complete_perapp_rules
patch_gpu_knob_path
uperf_start
sh $SCRIPT_PATH/closedloop_sched.sh >/dev/null 2>&1 &
